# Generated by Django 3.2.15 on 2022-09-03 05:58

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(blank=True, default=None, max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='firstname must string and should not be less than 3 and greater than 12', regex='[A-Za-z]{3}([A-Za-z]+ ?)*')])),
                ('Lastname', models.CharField(blank=True, default=None, max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='lastname must string and should not be less than 3 and greater than 12', regex='[A-Za-z]{3}([A-Za-z]+ ?)*')])),
                ('Email', models.EmailField(blank=True, default=None, max_length=50, null=True)),
                ('Username', models.CharField(blank=True, default=None, max_length=60, null=True, unique=True)),
                ('Password', models.CharField(blank=True, default=None, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='password must contain 8 letters and a captail letter and a special character ', regex='^.*(?=.{8,})(?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=]).*$')])),
                ('MobileNumber', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 14 digits allowed.", regex='^\\+?1?\\d{9,14}$')])),
                ('DeviceToken', models.CharField(default=None, max_length=255)),
                ('CreatedOn', models.DateTimeField(default=datetime.datetime.today)),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Doctor_Data',
            },
        ),
    ]
