# Generated by Django 3.2.15 on 2022-09-03 06:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FromDate', models.DateField()),
                ('ToDate', models.DateField()),
                ('FromTIme', models.TimeField(default=None)),
                ('ToTime', models.TimeField()),
                ('CurrentDate', models.DateTimeField(auto_now_add=True)),
                ('AppointmentType', models.CharField(default=None, max_length=250)),
                ('Fees', models.IntegerField(default=None)),
                ('CreatedOn', models.DateTimeField(default=datetime.datetime.today)),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('DId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Schedule', to='Doctor.doctormodel')),
            ],
            options={
                'db_table': 'Doctor_Scheduler',
            },
        ),
    ]
