# Generated by Django 3.2.15 on 2022-09-03 07:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_doctorscheduler'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symptom', models.CharField(max_length=250)),
                ('comments', models.TextField()),
                ('CreatedOn', models.DateTimeField(default=datetime.datetime.today)),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'symptomtable',
            },
        ),
        migrations.CreateModel(
            name='AppointmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Specialization', models.CharField(max_length=200)),
                ('CurrentDate', models.DateTimeField(auto_now_add=True)),
                ('Fees', models.IntegerField(default=None)),
                ('CreatedOn', models.DateTimeField(default=datetime.datetime.today)),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('DoctorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Appointments', to='Doctor.doctormodel')),
                ('ScheduleId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Scheduleid', to='Doctor.doctorscheduler')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='User.usermodel')),
                ('symptoms', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='symptoms_id', to='User.symptoms')),
            ],
            options={
                'db_table': 'User_Appointment',
            },
        ),
    ]
